[build-system]
requires = ["setuptools>=46.4", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tatsu/_version.py"
write_to_template = "__version__ = \"{version}\"\n"
